server:
  port: 3001

spring:
  # 连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/itripdb?serverTimezone=GMT-8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

