server:
  port: 1001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itripdb?serverTimezone=GMT-8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      # 设置全局逻辑删除字段
      logic-delete-field: is_deleted #逻辑字段名称
      logic-delete-value: 1 #逻辑已删除的值
      logic-not-delete-value: 0 #逻辑未删除的值